title: Martin Kraft
author: Martin Kraft
email: martin@upspin.org
description: Personal Blog
github_username:  mkraft
show_excerpts: true
theme: jekyll-theme-hacker
url: http://martin.upspin.org/
github: [metadata]